### ISSUE TITLE
Error on installation.

### ISSUE THREAD

**Issue by brunosarlo** [modoolar/scrummer#2]
Hello. Looking forward to test this modules for our organization.

Running this docker image: https://github.com/minhng92/odoo-11-docker-compose

Have this error currently. Any help appreciated.
 
`Error:
Odoo Server Error

Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/odoo/models.py", line 967, in _validate_fields
    check(self)
  File "/usr/lib/python3/dist-packages/odoo/addons/base/ir/ir_ui_view.py", line 333, in _check_xml
    view_def = view.read_combined(['arch'])
  File "/usr/lib/python3/dist-packages/odoo/addons/base/ir/ir_ui_view.py", line 717, in read_combined
    arch = self.apply_view_inheritance(arch_tree, root.id, self.model)
  File "/usr/lib/python3/dist-packages/odoo/addons/base/ir/ir_ui_view.py", line 666, in apply_view_inheritance
    source = self.apply_inheritance_specs(source, specs_tree, view_id)
  File "/usr/lib/python3/dist-packages/odoo/addons/base/ir/ir_ui_view.py", line 644, in apply_inheritance_specs
    self.raise_view_error(_("Element '%s' cannot be located in parent view") % tag, inherit_id)
  File "/usr/lib/python3/dist-packages/odoo/addons/base/ir/ir_ui_view.py", line 506, in raise_view_error
    raise ValueError(message)
ValueError: Element '<xpath expr="//button[@t-if='record.task_needaction_count.raw_value']">' cannot be located in parent view

Error context:
View `project.project.kanban`
[view_id: 613, xml_id: n/a, model: project.project, parent_id: 382]

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/odoo/tools/convert.py", line 741, in parse
    self._tags[rec.tag](rec, de, mode=mode)
  File "/usr/lib/python3/dist-packages/odoo/tools/convert.py", line 651, in _tag_record
    id = self.env(context=rec_context)['ir.model.data']._update(rec_model, self.module, res, rec_id or False, not self.isnoupdate(data_node), noupdate=self.isnoupdate(data_node), mode=self.mode)
  File "/usr/lib/python3/dist-packages/odoo/addons/base/ir/ir_model.py", line 1469, in _update
    record = record.create(values)
  File "/usr/lib/python3/dist-packages/odoo/addons/base/ir/ir_ui_view.py", line 401, in create
    return super(View, self).create(self._compute_defaults(values))
  File "/mnt/extra-addons/web_syncer/models/syncer.py", line 127, in create
    new = super(Base, self).create(vals)
  File "/usr/lib/python3/dist-packages/odoo/models.py", line 3286, in create
    self._fields[key].determine_inverse(record)
  File "/usr/lib/python3/dist-packages/odoo/fields.py", line 1081, in determine_inverse
    getattr(records, self.inverse)()
  File "/usr/lib/python3/dist-packages/odoo/addons/base/ir/ir_ui_view.py", line 269, in _inverse_arch
    view.write(data)
  File "/usr/lib/python3/dist-packages/odoo/addons/base/ir/ir_ui_view.py", line 417, in write
    return super(View, self).write(self._compute_defaults(vals))
  File "/mnt/extra-addons/web_syncer/models/syncer.py", line 106, in write
    return super(Base, self).write(vals)
  File "/usr/lib/python3/dist-packages/odoo/models.py", line 3008, in write
    self._write(old_vals)
  File "/mnt/extra-addons/web_syncer/models/syncer.py", line 93, in _write
    return super(Base, self)._write(vals)
  File "/usr/lib/python3/dist-packages/odoo/models.py", line 3161, in _write
    self._validate_fields(vals)
  File "/usr/lib/python3/dist-packages/odoo/models.py", line 971, in _validate_fields
    raise ValidationError("%s\n\n%s" % (_("Error while validating constraint"), tools.ustr(e)))
odoo.exceptions.ValidationError: ('Error while validating constraint\n\nElement \'<xpath expr="//button[@t-if=\'record.task_needaction_count.raw_value\']">\' cannot be located in parent view\n\nError context:\nView `project.project.kanban`\n[view_id: 613, xml_id: n/a, model: project.project, parent_id: 382]', None)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/odoo/http.py", line 646, in _handle_exception
    return super(JsonRequest, self)._handle_exception(exception)
  File "/usr/lib/python3/dist-packages/odoo/http.py", line 307, in _handle_exception
    raise pycompat.reraise(type(exception), exception, sys.exc_info()[2])
  File "/usr/lib/python3/dist-packages/odoo/tools/pycompat.py", line 87, in reraise
    raise value
  File "/usr/lib/python3/dist-packages/odoo/http.py", line 683, in dispatch
    result = self._call_function(**self.params)
  File "/usr/lib/python3/dist-packages/odoo/http.py", line 339, in _call_function
    return checked_call(self.db, *args, **kwargs)
  File "/usr/lib/python3/dist-packages/odoo/service/model.py", line 97, in wrapper
    return f(dbname, *args, **kwargs)
  File "/usr/lib/python3/dist-packages/odoo/http.py", line 332, in checked_call
    result = self.endpoint(*a, **kw)
  File "/mnt/extra-addons/web_syncer/http.py", line 9, in __call__
    result = self.method(*args, **kw)
  File "/usr/lib/python3/dist-packages/odoo/http.py", line 512, in response_wrap
    response = f(*args, **kw)
  File "/usr/lib/python3/dist-packages/odoo/addons/web/controllers/main.py", line 934, in call_button
    action = self._call_kw(model, method, args, {})
  File "/usr/lib/python3/dist-packages/odoo/addons/web/controllers/main.py", line 922, in _call_kw
    return call_kw(request.env[model], method, args, kwargs)
  File "/usr/lib/python3/dist-packages/odoo/api.py", line 689, in call_kw
    return call_kw_multi(method, model, args, kwargs)
  File "/usr/lib/python3/dist-packages/odoo/api.py", line 680, in call_kw_multi
    result = method(recs, *args, **kwargs)
  File "<decorator-gen-39>", line 2, in button_immediate_install
  File "/usr/lib/python3/dist-packages/odoo/addons/base/module/module.py", line 71, in check_and_log
    return method(self, *args, **kwargs)
  File "/usr/lib/python3/dist-packages/odoo/addons/base/module/module.py", line 448, in button_immediate_install
    return self._button_immediate_function(type(self).button_install)
  File "/usr/lib/python3/dist-packages/odoo/addons/base/module/module.py", line 541, in _button_immediate_function
    modules.registry.Registry.new(self._cr.dbname, update_module=True)
  File "/usr/lib/python3/dist-packages/odoo/modules/registry.py", line 85, in new
    odoo.modules.load_modules(registry._db, force_demo, status, update_module)
  File "/usr/lib/python3/dist-packages/odoo/modules/loading.py", line 343, in load_modules
    loaded_modules, update_module)
  File "/usr/lib/python3/dist-packages/odoo/modules/loading.py", line 242, in load_marked_modules
    loaded, processed = load_module_graph(cr, graph, progressdict, report=report, skip_modules=loaded_modules, perform_checks=perform_checks)
  File "/usr/lib/python3/dist-packages/odoo/modules/loading.py", line 156, in load_module_graph
    _load_data(cr, module_name, idref, mode, kind='data')
  File "/usr/lib/python3/dist-packages/odoo/modules/loading.py", line 94, in _load_data
    tools.convert_file(cr, module_name, filename, idref, mode, noupdate, kind, report)
  File "/usr/lib/python3/dist-packages/odoo/tools/convert.py", line 788, in convert_file
    convert_xml_import(cr, module, fp, idref, mode, noupdate, report)
  File "/usr/lib/python3/dist-packages/odoo/tools/convert.py", line 849, in convert_xml_import
    obj.parse(doc.getroot(), mode=mode)
  File "/usr/lib/python3/dist-packages/odoo/tools/convert.py", line 748, in parse
    exc_info[2]
  File "/usr/lib/python3/dist-packages/odoo/tools/pycompat.py", line 86, in reraise
    raise value.with_traceback(tb)
  File "/usr/lib/python3/dist-packages/odoo/tools/convert.py", line 741, in parse
    self._tags[rec.tag](rec, de, mode=mode)
  File "/usr/lib/python3/dist-packages/odoo/tools/convert.py", line 651, in _tag_record
    id = self.env(context=rec_context)['ir.model.data']._update(rec_model, self.module, res, rec_id or False, not self.isnoupdate(data_node), noupdate=self.isnoupdate(data_node), mode=self.mode)
  File "/usr/lib/python3/dist-packages/odoo/addons/base/ir/ir_model.py", line 1469, in _update
    record = record.create(values)
  File "/usr/lib/python3/dist-packages/odoo/addons/base/ir/ir_ui_view.py", line 401, in create
    return super(View, self).create(self._compute_defaults(values))
  File "/mnt/extra-addons/web_syncer/models/syncer.py", line 127, in create
    new = super(Base, self).create(vals)
  File "/usr/lib/python3/dist-packages/odoo/models.py", line 3286, in create
    self._fields[key].determine_inverse(record)
  File "/usr/lib/python3/dist-packages/odoo/fields.py", line 1081, in determine_inverse
    getattr(records, self.inverse)()
  File "/usr/lib/python3/dist-packages/odoo/addons/base/ir/ir_ui_view.py", line 269, in _inverse_arch
    view.write(data)
  File "/usr/lib/python3/dist-packages/odoo/addons/base/ir/ir_ui_view.py", line 417, in write
    return super(View, self).write(self._compute_defaults(vals))
  File "/mnt/extra-addons/web_syncer/models/syncer.py", line 106, in write
    return super(Base, self).write(vals)
  File "/usr/lib/python3/dist-packages/odoo/models.py", line 3008, in write
    self._write(old_vals)
  File "/mnt/extra-addons/web_syncer/models/syncer.py", line 93, in _write
    return super(Base, self)._write(vals)
  File "/usr/lib/python3/dist-packages/odoo/models.py", line 3161, in _write
    self._validate_fields(vals)
  File "/usr/lib/python3/dist-packages/odoo/models.py", line 971, in _validate_fields
    raise ValidationError("%s\n\n%s" % (_("Error while validating constraint"), tools.ustr(e)))
odoo.tools.convert.ParseError: "Error while validating constraint

Element '<xpath expr="//button[@t-if='record.task_needaction_count.raw_value']">' cannot be located in parent view

Error context:
View `project.project.kanban`
[view_id: 613, xml_id: n/a, model: project.project, parent_id: 382]
None" while parsing /mnt/extra-addons/project_agile/views/project_project_views.xml:191, near
<record model="ir.ui.view" id="view_project_kanban">
        <field name="name">project.project.kanban</field>
        <field name="model">project.project</field>
        <field name="inherit_id" ref="project.view_project_kanban"/>
        <field name="priority" eval="100"/>
        <field name="arch" type="xml">
            <data><field name="partner_id" position="after">
                <field name="type_id"/>
            </field>

            <xpath expr="//div[hasclass('o_primary')]/span[1]" position="after">
                <span t-if="record.type_id.value">
                    <t t-esc="record.type_id.value"/>
                </span>

            </xpath>

            <xpath expr="//div[hasclass('o_kanban_manage_reports')]/div[2]" position="before">
                <div>
                    <a name="open_epics" type="object">Epics</a>
                </div>
                <div>
                    <a name="open_user_stories" type="object">User Stories</a>
                </div>

            </xpath>

            <xpath expr="//a[text()='Tasks']" position="attributes">
                <attribute name="name">open_tasks</attribute>
                <attribute name="type">object</attribute>
            </xpath>

            <xpath expr="//t[@t-esc='record.task_count.value']/../../.." position="attributes">
                <attribute name="name">open_tasks</attribute>
                <attribute name="type">object</attribute>
            </xpath>

            <xpath expr="//button[@t-if='record.task_needaction_count.raw_value']" position="attributes">
                <attribute name="name">open_tasks</attribute>
                <attribute name="type">object</attribute>
            </xpath>
        </data></field>
    </record>`

**Comment by igor-mitin** [comment]
Make the following changes.
The truth about commenting `<xpath expr="//a[text()='Tasks']" position="attributes">` I'm not sure what's right.

```diff
diff --git a/project_agile/views/project_agile.xml b/project_agile/views/project_agile.xml
index b0b8dc9..27c2a6c 100644
--- a/project_agile/views/project_agile.xml
+++ b/project_agile/views/project_agile.xml
@@ -42,12 +42,12 @@
             </button>
         </xpath>
 
-        <xpath expr="//div[@t-if='grouped_tasks']//thead//th[text() = 'Stage']" position="before">
+        <xpath expr="//div[@t-if='tasks']//thead//th[text() = 'Stage']" position="before">
             <th>Type</th>
             <th>Priority</th>
         </xpath>
 
-        <xpath expr="//div[@t-if='grouped_tasks']//span[@t-field='task.name']" position="after">
+        <xpath expr="//div[@t-if='tasks']//span[@t-field='task.name']" position="after">
             <td>
                 <img style="width: 20px; vertical-align: top; text-align: center;" t-if="task.type_id.icon"
                      t-att-src="'data:image/png;base64,%s' % to_text(task.type_id.icon)"
diff --git a/project_agile/views/project_project_views.xml b/project_agile/views/project_project_views.xml
index 073be90..b460f86 100644
--- a/project_agile/views/project_project_views.xml
+++ b/project_agile/views/project_project_views.xml
@@ -215,18 +215,18 @@
                 </div>
 
             </xpath>
-
+<!--
             <xpath expr="//a[text()='Tasks']" position="attributes">
                 <attribute name="name">open_tasks</attribute>
                 <attribute name="type">object</attribute>
             </xpath>
-
+-->
             <xpath expr="//t[@t-esc='record.task_count.value']/../../.." position="attributes">
                 <attribute name="name">open_tasks</attribute>
                 <attribute name="type">object</attribute>
             </xpath>
 
-            <xpath expr="//button[@t-if='record.task_needaction_count.raw_value']" position="attributes">
+            <xpath expr="//a[@t-if='record.task_needaction_count.raw_value']" position="attributes">
                 <attribute name="name">open_tasks</attribute>
                 <attribute name="type">object</attribute>
             </xpath>
diff --git a/project_agile_jira/data/crons.xml b/project_agile_jira/data/crons.xml
index 83bd3ed..5a84e9b 100644
--- a/project_agile_jira/data/crons.xml
+++ b/project_agile_jira/data/crons.xml
@@ -7,12 +7,14 @@
     <data noupdate="1">
         <record model="ir.cron" id="project_agile_jira_request_cron">
             <field name='name'>Proccess JIRA requests</field>
+            <field name="model_id" ref="model_project_agile_jira_worker"/>
             <field name='interval_number'>30</field>
             <field name='interval_type'>minutes</field>
             <field name="numbercall">-1</field>
-            <field name="active">True</field>
-            <field name="model">project.agile.jira.worker</field>
+            <field eval="True" name="active" />
             <field name="function">execute_requests</field>
+            <field name="state">code</field>
+            <field name="code">model.execute_requests()</field>
         </record>
     </data>
 </odoo>
diff --git a/project_agile_jira/models/jira_worker.py b/project_agile_jira/models/jira_worker.py
index 1cb3f72..506538f 100644
--- a/project_agile_jira/models/jira_worker.py
+++ b/project_agile_jira/models/jira_worker.py
@@ -102,7 +102,7 @@ class JiraWorker(models.AbstractModel):
                 worklogs.append({
                     "user": worklog.author.displayName,
                     "duration": worklog.timeSpentSeconds/3600,
-                    "description": worklog.comment,
+                    "description": getattr(worklog, 'comment', ""),
                     "issue": issue.key,
                 })
 
diff --git a/project_workflow/models/project_workflow.py b/project_workflow/models/project_workflow.py
index 054071d..a6c116f 100644
--- a/project_workflow/models/project_workflow.py
+++ b/project_workflow/models/project_workflow.py
@@ -2,7 +2,7 @@
 # License LGPLv3.0 or later (https://www.gnu.org/licenses/lgpl-3.0.en.html).
 
 from odoo import models, fields, api, exceptions, _
-from odoo.tools import safe_eval
+from odoo.tools.safe_eval import safe_eval
 
 
 class Workflow(models.Model):
```

**Comment by igor-mitin** [comment]
Reason for error `expr="//a[text()='Tasks']"`
For more information, see the Pull Request - https://github.com/modoolar/scrummer/pull/3

**Comment by pnajman-modoolar** [comment]
Hi @brunosarlo . @igor-mitin ,

We have just released a new version. In this version we've decided to remove everything related to the project portal. The reason behind it is Odoo's constant development of that segment and thus making it very unstable from version to version. So, until that part of Odoo becomes more stable we'll just have to postpone that feature.

Kind Regards,
Petar
