### ISSUE TITLE
Broken Project after install Scrummer

### ISSUE THREAD

**Issue by stanta** [modoolar/scrummer#4]
After Scrummer install 
When try to enter Projects 
got 
Odoo Server Error

Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/odoo/http.py", line 650, in _handle_exception
    return super(JsonRequest, self)._handle_exception(exception)
  File "/usr/lib/python3/dist-packages/odoo/http.py", line 310, in _handle_exception
    raise pycompat.reraise(type(exception), exception, sys.exc_info()[2])
  File "/usr/lib/python3/dist-packages/odoo/tools/pycompat.py", line 87, in reraise
    raise value
  File "/usr/lib/python3/dist-packages/odoo/http.py", line 692, in dispatch
    result = self._call_function(**self.params)
  File "/usr/lib/python3/dist-packages/odoo/http.py", line 342, in _call_function
    return checked_call(self.db, *args, **kwargs)
  File "/usr/lib/python3/dist-packages/odoo/service/model.py", line 97, in wrapper
    return f(dbname, *args, **kwargs)
  File "/usr/lib/python3/dist-packages/odoo/http.py", line 335, in checked_call
    result = self.endpoint(*a, **kw)
  File "/mnt/extra-addons/web_syncer/http.py", line 9, in __call__
    result = self.method(*args, **kw)
  File "/usr/lib/python3/dist-packages/odoo/http.py", line 515, in response_wrap
    response = f(*args, **kw)
  File "/usr/lib/python3/dist-packages/odoo/addons/web/controllers/main.py", line 931, in call_kw
    return self._call_kw(model, method, args, kwargs)
  File "/usr/lib/python3/dist-packages/odoo/addons/web/controllers/main.py", line 923, in _call_kw
    return call_kw(request.env[model], method, args, kwargs)
  File "/usr/lib/python3/dist-packages/odoo/api.py", line 687, in call_kw
    return call_kw_model(method, model, args, kwargs)
  File "/usr/lib/python3/dist-packages/odoo/api.py", line 672, in call_kw_model
    result = method(recs, *args, **kwargs)
  File "/usr/lib/python3/dist-packages/odoo/models.py", line 1295, in load_views
    for [v_id, v_type] in views
  File "/usr/lib/python3/dist-packages/odoo/models.py", line 1295, in <dictcomp>
    for [v_id, v_type] in views
  File "/usr/lib/python3/dist-packages/odoo/addons/mail/models/mail_thread.py", line 370, in fields_view_get
    res = super(MailThread, self).fields_view_get(view_id=view_id, view_type=view_type, toolbar=toolbar, submenu=submenu)
  File "/usr/lib/python3/dist-packages/odoo/models.py", line 1374, in fields_view_get
    result = self._fields_view_get(view_id=view_id, view_type=view_type, toolbar=toolbar, submenu=submenu)
  File "/usr/lib/python3/dist-packages/odoo/models.py", line 1337, in _fields_view_get
    root_view = View.browse(view_id).read_combined(['id', 'name', 'field_parent', 'type', 'model', 'arch'])
  File "/usr/lib/python3/dist-packages/odoo/addons/base/ir/ir_ui_view.py", line 720, in read_combined
    arch = self.apply_view_inheritance(arch_tree, root.id, self.model)
  File "/usr/lib/python3/dist-packages/odoo/addons/base/ir/ir_ui_view.py", line 669, in apply_view_inheritance
    source = self.apply_inheritance_specs(source, specs_tree, view_id)
  File "/usr/lib/python3/dist-packages/odoo/addons/base/ir/ir_ui_view.py", line 647, in apply_inheritance_specs
    self.raise_view_error(_("Element '%s' cannot be located in parent view") % tag, inherit_id)
  File "/usr/lib/python3/dist-packages/odoo/addons/base/ir/ir_ui_view.py", line 509, in raise_view_error
    raise ValueError(message)
ValueError: Элемент '<xpath expr="//a[text()='Tasks']">' не может находится в родительском виде

Ошибка контекста:
Просмотр `project.project.kanban`
[view_id: 1254, xml_id: project_agile.view_project_kanban, model: project.project, parent_id: 384]

**Comment by igor-mitin** [comment]
Посмотрите мой Pull request - там это поправлено и разъяснено из-за чего это.
Собственно сама поправка, самый первый файл =  project_agile/views/project_project_views.xml
https://github.com/modoolar/scrummer/pull/3/commits/fe1e6a094305470a192f995b6fe30dc19c25c88b

Пишу по русски, т.к. вижу что сообщение об ошибке на русском ;-)

**Comment by stanta** [comment]
Pulled your rep but it didn't help.
now when trying to install  over work DB error is
The operation cannot be completed, probably due to the following:
- deletion: you may be trying to delete a record while other records still reference it
- creation/update: a mandatory field is not correctly set

[объект со ссылкой: project_type - project.type]

**Comment by igor-mitin** [comment]
Try the source from my fork - https://github.com/igor-mitin/scrummer
There's a lot that has already been fixed.

And a huge request to insert in the comment the complete error trace.
Here is an example - https://github.com/modoolar/scrummer/issues/2

Those. Do not cut the diagnostic output at the end.

**Comment by pnajman-modoolar** [comment]
Hi @stanta,

We've just released a new version.
I hope this release will fix your issues.

Regards,
Petar
