### ISSUE TITLE
Question: Is the the project updated with latest changes ?

### ISSUE THREAD

**Issue by sbpro86** [modoolar/scrummer#5]
Hello,

I was just trying to test this awesome project management tool built on Odoo and I faced some errors at installation step.

I also see that the latest commit date from 3 months ago so is the project still maintained by Modoolar and we should expect updates and fixes in the future ? or what is the plan for the project ?

Could we work on fixing issues and propose pull requests that will be reviewed and eventually merged ?

Thank you.

**Comment by pnajman-modoolar** [comment]
Hi @slimit ,

Yes, project is still maintained by us but unfortunately we had somewhat a "dry" period due to the daily work load.

Anyhow, we'll try to regularly push new updates as much as we can and of course we welcome contributions from anyone interested to help out. 

In case you wan to contribute with bugfix or a new feature please follow OCA's guidelines which can be found [here](https://github.com/OCA/maintainer-tools) 

Thanks,
Petar

**Comment by zzhumphreyt** [comment]
Thank you for updating the repository. The project_key project seems to be missing though. When I tried to install the project_agile_scrum app I got an error in Odoo 11 that the project_key dependency was missing. I tried to get most other dependencies by looking at the other repos under modoolar, but I couldn't find it where I thought to look, under the project repo. Can this be added?

**Comment by nogueira-raphael** [comment]
@zzhumphreyt
The OCA "project" repository is a dependency of the scrummer and project_agile, to install them first download the OCA repository.
[OCA/Project](https://github.com/OCA/project)

**Comment by zzhumphreyt** [comment]
I found the project_key module and installed it without issue. Now when installing project_agile I get the below error. How can I solve this?

Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/odoo/models.py", line 967, in _validate_fields
    check(self)
  File "/usr/lib/python3/dist-packages/odoo/addons/base/ir/ir_ui_view.py", line 333, in _check_xml
    view_def = view.read_combined(['arch'])
  File "/usr/lib/python3/dist-packages/odoo/addons/base/ir/ir_ui_view.py", line 717, in read_combined
    arch = self.apply_view_inheritance(arch_tree, root.id, self.model)
  File "/usr/lib/python3/dist-packages/odoo/addons/base/ir/ir_ui_view.py", line 666, in apply_view_inheritance
    source = self.apply_inheritance_specs(source, specs_tree, view_id)
  File "/usr/lib/python3/dist-packages/odoo/addons/base/ir/ir_ui_view.py", line 644, in apply_inheritance_specs
    self.raise_view_error(_("Element '%s' cannot be located in parent view") % tag, inherit_id)
  File "/usr/lib/python3/dist-packages/odoo/addons/base/ir/ir_ui_view.py", line 506, in raise_view_error
    raise ValueError(message)
ValueError: Element '<xpath expr="//button[@t-if='record.task_needaction_count.raw_value']">' cannot be located in parent view

Error context:
View `project.project.kanban`
[view_id: 1763, xml_id: n/a, model: project.project, parent_id: 898]

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/odoo/tools/convert.py", line 741, in parse
    self._tags[rec.tag](rec, de, mode=mode)
  File "/usr/lib/python3/dist-packages/odoo/tools/convert.py", line 651, in _tag_record
    id = self.env(context=rec_context)['ir.model.data']._update(rec_model, self.module, res, rec_id or False, not self.isnoupdate(data_node), noupdate=self.isnoupdate(data_node), mode=self.mode)
  File "/usr/lib/python3/dist-packages/odoo/addons/base/ir/ir_model.py", line 1469, in _update
    record = record.create(values)
  File "/usr/lib/python3/dist-packages/odoo/addons/base/ir/ir_ui_view.py", line 401, in create
    return super(View, self).create(self._compute_defaults(values))
  File "/var/lib/odoo/addons/11.0/web_syncer/models/syncer.py", line 127, in create
    new = super(Base, self).create(vals)
  File "/usr/lib/python3/dist-packages/odoo/models.py", line 3286, in create
    self._fields[key].determine_inverse(record)
  File "/usr/lib/python3/dist-packages/odoo/fields.py", line 1081, in determine_inverse
    getattr(records, self.inverse)()
  File "/usr/lib/python3/dist-packages/odoo/addons/base/ir/ir_ui_view.py", line 269, in _inverse_arch
    view.write(data)
  File "/usr/lib/python3/dist-packages/odoo/addons/base/ir/ir_ui_view.py", line 417, in write
    return super(View, self).write(self._compute_defaults(vals))
  File "/var/lib/odoo/addons/11.0/web_syncer/models/syncer.py", line 106, in write
    return super(Base, self).write(vals)
  File "/usr/lib/python3/dist-packages/odoo/models.py", line 3008, in write
    self._write(old_vals)
  File "/var/lib/odoo/addons/11.0/web_syncer/models/syncer.py", line 93, in _write
    return super(Base, self)._write(vals)
  File "/usr/lib/python3/dist-packages/odoo/models.py", line 3161, in _write
    self._validate_fields(vals)
  File "/usr/lib/python3/dist-packages/odoo/models.py", line 971, in _validate_fields
    raise ValidationError("%s\n\n%s" % (_("Error while validating constraint"), tools.ustr(e)))
odoo.exceptions.ValidationError: ('Error while validating constraint\n\nElement \'<xpath expr="//button[@t-if=\'record.task_needaction_count.raw_value\']">\' cannot be located in parent view\n\nError context:\nView `project.project.kanban`\n[view_id: 1763, xml_id: n/a, model: project.project, parent_id: 898]', None)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/odoo/http.py", line 646, in _handle_exception
    return super(JsonRequest, self)._handle_exception(exception)
  File "/usr/lib/python3/dist-packages/odoo/http.py", line 307, in _handle_exception
    raise pycompat.reraise(type(exception), exception, sys.exc_info()[2])
  File "/usr/lib/python3/dist-packages/odoo/tools/pycompat.py", line 87, in reraise
    raise value
  File "/usr/lib/python3/dist-packages/odoo/http.py", line 683, in dispatch
    result = self._call_function(**self.params)
  File "/usr/lib/python3/dist-packages/odoo/http.py", line 339, in _call_function
    return checked_call(self.db, *args, **kwargs)
  File "/usr/lib/python3/dist-packages/odoo/service/model.py", line 97, in wrapper
    return f(dbname, *args, **kwargs)
  File "/usr/lib/python3/dist-packages/odoo/http.py", line 332, in checked_call
    result = self.endpoint(*a, **kw)
  File "/var/lib/odoo/addons/11.0/web_syncer/http.py", line 9, in __call__
    result = self.method(*args, **kw)
  File "/usr/lib/python3/dist-packages/odoo/http.py", line 512, in response_wrap
    response = f(*args, **kw)
  File "/usr/lib/python3/dist-packages/odoo/addons/web/controllers/main.py", line 934, in call_button
    action = self._call_kw(model, method, args, {})
  File "/usr/lib/python3/dist-packages/odoo/addons/web/controllers/main.py", line 922, in _call_kw
    return call_kw(request.env[model], method, args, kwargs)
  File "/usr/lib/python3/dist-packages/odoo/api.py", line 689, in call_kw
    return call_kw_multi(method, model, args, kwargs)
  File "/usr/lib/python3/dist-packages/odoo/api.py", line 680, in call_kw_multi
    result = method(recs, *args, **kwargs)
  File "<decorator-gen-39>", line 2, in button_immediate_install
  File "/usr/lib/python3/dist-packages/odoo/addons/base/module/module.py", line 71, in check_and_log
    return method(self, *args, **kwargs)
  File "/usr/lib/python3/dist-packages/odoo/addons/base/module/module.py", line 448, in button_immediate_install
    return self._button_immediate_function(type(self).button_install)
  File "/usr/lib/python3/dist-packages/odoo/addons/base/module/module.py", line 541, in _button_immediate_function
    modules.registry.Registry.new(self._cr.dbname, update_module=True)
  File "/usr/lib/python3/dist-packages/odoo/modules/registry.py", line 85, in new
    odoo.modules.load_modules(registry._db, force_demo, status, update_module)
  File "/usr/lib/python3/dist-packages/odoo/modules/loading.py", line 343, in load_modules
    loaded_modules, update_module)
  File "/usr/lib/python3/dist-packages/odoo/modules/loading.py", line 242, in load_marked_modules
    loaded, processed = load_module_graph(cr, graph, progressdict, report=report, skip_modules=loaded_modules, perform_checks=perform_checks)
  File "/usr/lib/python3/dist-packages/odoo/modules/loading.py", line 156, in load_module_graph
    _load_data(cr, module_name, idref, mode, kind='data')
  File "/usr/lib/python3/dist-packages/odoo/modules/loading.py", line 94, in _load_data
    tools.convert_file(cr, module_name, filename, idref, mode, noupdate, kind, report)
  File "/usr/lib/python3/dist-packages/odoo/tools/convert.py", line 788, in convert_file
    convert_xml_import(cr, module, fp, idref, mode, noupdate, report)
  File "/usr/lib/python3/dist-packages/odoo/tools/convert.py", line 849, in convert_xml_import
    obj.parse(doc.getroot(), mode=mode)
  File "/usr/lib/python3/dist-packages/odoo/tools/convert.py", line 748, in parse
    exc_info[2]
  File "/usr/lib/python3/dist-packages/odoo/tools/pycompat.py", line 86, in reraise
    raise value.with_traceback(tb)
  File "/usr/lib/python3/dist-packages/odoo/tools/convert.py", line 741, in parse
    self._tags[rec.tag](rec, de, mode=mode)
  File "/usr/lib/python3/dist-packages/odoo/tools/convert.py", line 651, in _tag_record
    id = self.env(context=rec_context)['ir.model.data']._update(rec_model, self.module, res, rec_id or False, not self.isnoupdate(data_node), noupdate=self.isnoupdate(data_node), mode=self.mode)
  File "/usr/lib/python3/dist-packages/odoo/addons/base/ir/ir_model.py", line 1469, in _update
    record = record.create(values)
  File "/usr/lib/python3/dist-packages/odoo/addons/base/ir/ir_ui_view.py", line 401, in create
    return super(View, self).create(self._compute_defaults(values))
  File "/var/lib/odoo/addons/11.0/web_syncer/models/syncer.py", line 127, in create
    new = super(Base, self).create(vals)
  File "/usr/lib/python3/dist-packages/odoo/models.py", line 3286, in create
    self._fields[key].determine_inverse(record)
  File "/usr/lib/python3/dist-packages/odoo/fields.py", line 1081, in determine_inverse
    getattr(records, self.inverse)()
  File "/usr/lib/python3/dist-packages/odoo/addons/base/ir/ir_ui_view.py", line 269, in _inverse_arch
    view.write(data)
  File "/usr/lib/python3/dist-packages/odoo/addons/base/ir/ir_ui_view.py", line 417, in write
    return super(View, self).write(self._compute_defaults(vals))
  File "/var/lib/odoo/addons/11.0/web_syncer/models/syncer.py", line 106, in write
    return super(Base, self).write(vals)
  File "/usr/lib/python3/dist-packages/odoo/models.py", line 3008, in write
    self._write(old_vals)
  File "/var/lib/odoo/addons/11.0/web_syncer/models/syncer.py", line 93, in _write
    return super(Base, self)._write(vals)
  File "/usr/lib/python3/dist-packages/odoo/models.py", line 3161, in _write
    self._validate_fields(vals)
  File "/usr/lib/python3/dist-packages/odoo/models.py", line 971, in _validate_fields
    raise ValidationError("%s\n\n%s" % (_("Error while validating constraint"), tools.ustr(e)))
odoo.tools.convert.ParseError: "Error while validating constraint

Element '<xpath expr="//button[@t-if='record.task_needaction_count.raw_value']">' cannot be located in parent view

Error context:
View `project.project.kanban`
[view_id: 1763, xml_id: n/a, model: project.project, parent_id: 898]
None" while parsing /var/lib/odoo/addons/11.0/project_agile/views/project_project_view.xml:202, near
<record model="ir.ui.view" id="view_project_kanban">
        <field name="name">project.project.kanban</field>
        <field name="model">project.project</field>
        <field name="inherit_id" ref="project.view_project_kanban"/>
        <field name="priority" eval="100"/>
        <field name="arch" type="xml">
            <data><field name="partner_id" position="after">
                <field name="type_id"/>
            </field>

            <xpath expr="//div[hasclass('o_primary')]/span[1]" position="after">
                <span t-if="record.type_id.value">
                    <t t-esc="record.type_id.value"/>
                </span>

            </xpath>


            <xpath expr="//div[hasclass('o_kanban_manage_reports')]/div[2]" position="before">
                <div>
                    <a name="open_epics" type="object">Epics</a>
                </div>
                <div>
                    <a name="open_user_stories" type="object">User Stories</a>
                </div>

            </xpath>

            <xpath expr="//a[@name='%(project.action_project_task_user_tree_filtered)d']" position="attributes">
                <attribute name="name">open_tasks</attribute>
                <attribute name="type">object</attribute>
            </xpath>

            <xpath expr="//t[@t-esc='record.task_count.value']/../../.." position="attributes">
                <attribute name="name">open_tasks</attribute>
                <attribute name="type">object</attribute>
            </xpath>

            <xpath expr="//button[@t-if='record.task_needaction_count.raw_value']" position="attributes">
                <attribute name="name">open_tasks</attribute>
                <attribute name="type">object</attribute>
            </xpath>
        </data></field>
    </record>

**Comment by zzhumphreyt** [comment]
BTW, I tried installing Scrummer from the official Odoo store and got the same error, even when using a brand new database. I'd love it if you all could fix these install issues. I get the impression Scrummer would be very useful so I'm hopeful to be able to evaluate it!

**Comment by pnajman-modoolar** [comment]
Hello

We've decided to return ``project_key`` module to the [project](https://github.com/modoolar/project) repository in order to have everything in one place, even though the module can be found under the [oca project repo](https://github.com/oca/project).

Regarding the latest issue, I'll take a look at it ASAP.
