### ISSUE TITLE
Cannot Map States to Project Board

### ISSUE THREAD

**Issue by cikciks** [modoolar/scrummer#6]
Hello,

I'm interest & trying to install this modules on Odoo 11 CE.
I have an issue to add item at workflow states to Project Board.

> Error:
> Odoo Server Error
> 
> Traceback (most recent call last):
>   File "/opt/odoo/server/odoo/fields.py", line 937, in __get__
>     value = record.env.cache.get(record, self)
>   File "/opt/odoo/server/odoo/api.py", line 960, in get
>     value = self._data[field][record.id][key]
> KeyError: <odoo.addons.web_syncer.api.SyncerEnvironment object at 0x7f7a2c459160>
> 
> During handling of the above exception, another exception occurred:
> 
> Traceback (most recent call last):
>   File "/opt/odoo/server/odoo/http.py", line 650, in _handle_exception
>     return super(JsonRequest, self)._handle_exception(exception)
>   File "/opt/odoo/server/odoo/http.py", line 310, in _handle_exception
>     raise pycompat.reraise(type(exception), exception, sys.exc_info()[2])
>   File "/opt/odoo/server/odoo/tools/pycompat.py", line 87, in reraise
>     raise value
>   File "/opt/odoo/server/odoo/http.py", line 692, in dispatch
>     result = self._call_function(**self.params)
>   File "/opt/odoo/server/odoo/http.py", line 342, in _call_function
>     return checked_call(self.db, *args, **kwargs)
>   File "/opt/odoo/server/odoo/service/model.py", line 97, in wrapper
>     return f(dbname, *args, **kwargs)
>   File "/opt/odoo/server/odoo/http.py", line 335, in checked_call
>     result = self.endpoint(*a, **kw)
>   File "/opt/odoo/server/addons-custom/modoolar/web/web_syncer/http.py", line 9, in __call__
>     result = self.method(*args, **kw)
>   File "/opt/odoo/server/odoo/http.py", line 515, in response_wrap
>     response = f(*args, **kw)
>   File "/opt/odoo/server/addons/web/controllers/main.py", line 934, in call_kw
>     return self._call_kw(model, method, args, kwargs)
>   File "/opt/odoo/server/addons/web/controllers/main.py", line 926, in _call_kw
>     return call_kw(request.env[model], method, args, kwargs)
>   File "/opt/odoo/server/odoo/api.py", line 689, in call_kw
>     return call_kw_multi(method, model, args, kwargs)
>   File "/opt/odoo/server/odoo/api.py", line 680, in call_kw_multi
>     result = method(recs, *args, **kwargs)
>   File "/opt/odoo/server/odoo/models.py", line 2601, in read
>     values[name] = field.convert_to_read(record[name], record, use_name_get)
>   File "/opt/odoo/server/odoo/models.py", line 4758, in __getitem__
>     return self._fields[key].__get__(self, type(self))
>   File "/opt/odoo/server/odoo/fields.py", line 941, in __get__
>     self.determine_value(record)
>   File "/opt/odoo/server/odoo/fields.py", line 1052, in determine_value
>     self.compute_value(recs)
>   File "/opt/odoo/server/odoo/fields.py", line 1008, in compute_value
>     self._compute_value(records)
>   File "/opt/odoo/server/odoo/fields.py", line 999, in _compute_value
>     getattr(records, self.compute)()
>   File "/opt/odoo/server/addons-custom/modoolar/project-agile/project_agile/models/project_agile_board.py", line 372, in _compute_workflow_ids
>     "project_ids.workflow_id"
>   File "/opt/odoo/server/odoo/models.py", line 4512, in mapped
>     recs = recs._mapped_func(operator.itemgetter(name))
>   File "/opt/odoo/server/odoo/models.py", line 4491, in _mapped_func
>     vals = [func(rec) for rec in self]
>   File "/opt/odoo/server/odoo/models.py", line 4491, in <listcomp>
>     vals = [func(rec) for rec in self]
>   File "/opt/odoo/server/odoo/models.py", line 4758, in __getitem__
>     return self._fields[key].__get__(self, type(self))
> KeyError: 'project_ids'

Could you help me to resolve this issue?

Regards

**Comment by agajic-modoolar** [comment]
Can you please provide exact steps for reproducing this bug?
Stacktrace does not help enough.
